services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./public/arts:/usr/src/app/public/arts  # Mounting local public folder
    depends_on:
     - php
     - mysql
     - phpmyadmin
  php:
    build: ./php
    ports:
      - "9000:80"
    volumes:
      - ./public/arts:/var/www/html/public/arts  # Mounting same folder to PHP container
    links:
      - mysql

  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: pkrim-art-gallery

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  react-art-volume: