services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
     - php
     - mysql
     - phpmyadmin
  php:
    build: ./php
    ports:
      - "80:80"
    links:
      - mysql

  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: pkrim-art-gallery

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

